name: CI

on: [push, pull_request]

jobs:
  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        php-versions: ['7.0', '7.1', '7.2', '7.3', '7.4']
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Setup PHP version and composer
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Install composer dependencies
        run: composer install
      - name: Run PHP linter
        run: |
          errors=$(find . -name \*.php ! -path "./vendor/*" -exec php -d display_errors=stderr -l {} 2>&1 >/dev/null \;) && echo "$errors" && test -z "$errors"
