name: CI

on: [push, pull_request]

jobs:
  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        php: ['7.0', '7.1', '7.2', '7.3', '7.4']
    steps:
      - uses: actions/checkout@v1
      - name: Use specified PHP Version
        run: |
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
          php -v
      - name: Install composer dependencies
        run: |
          composer install
      - name: Running PHP lint
        run: |
          find . -name \*.php -exec php -l {} >/dev/null \;
